### ISSUE TITLE
onLoad event not firing on background-image ?

### ISSUE THREAD

**Issue by mrdoinel** [imgix/imgix.js#101] opened 2016-05-09 10:22 UTC
It seems background-image never reach the onLoad callback.
The second onLoad (el.onload) will never be called because <el> is not an <img> element I guess :

```
imgix.setElementImageAfterLoad = function (el, imgUrl, callback) {
  var img = new Image();
  img.onload = function () {
    el.onload = function() {
      if (typeof callback === 'function') {
        callback(el, imgUrl);
      }
    };

    imgix.setElementImage(el, imgUrl);
  };
  if (el.hasAttribute('crossorigin')) {
    img.setAttribute('crossorigin', el.getAttribute('crossorigin'));
  }

  img.src = imgUrl;
};
```

**Comment by paulstraw** [comment] 2016-05-09 10:25
Hey @mrdoinel, it sounds like you're running into the Chrome regression in #97. I'm going to close this as a duplicate, but let me know if I've misunderstood something and I'll be happy to reopen this.

I'm also in the process of getting #100 wrapped up over the next couple of weeks, and when that's released, it will fix any `onLoad` related bugs by definition, since it removes all `onLoad` listeners.

**Closed by paulstraw** 2016-05-09 10:25 UTC

**Comment by mrdoinel** [comment] 2016-05-09 12:23
Thank you @paulstraw

One last comment, just to be sure you got the bug here :
```
    el.onload = function() {
      if (typeof callback === 'function') {
        callback(el, imgUrl);
      }
    };
```

**el.onload will never fire if el is not an img or an iframe**
